Fix broken use of Julia internals in newton
Reverts a performance optimization introduced in e3d2ce6 that broke with
the release of Julia 1.12:

    MethodError: no method matching pow_body(::UInt64, ::Float64)